### ISSUE TITLE
Would be nice to get a line number to more accurately determine if this is a false positive

### ISSUE THREAD

**Issue by jhsware** [KTH/evolene#6]
https://github.com/KTH/evolene/blob/d7805a103b4de3226822162cf7c870d0d5d9156d/modules/pipeline_steps/repo_supervisor_step.py#L79

**Comment by patricjansson** [comment]
To my knowlege that is not supported in https://github.com/auth0/repo-supervisor that we use. We could look into sonarcube or something more powerfull or you set this up using a separate Github Action workflow.
